apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-security-config
  namespace: midterm
data:
  cloudwatch-logs-config.json: |
    {
      "logGroupName": "/aws/eks/security-log-group",
      "logStreamName": "security-events",
      "filterPattern": "ERROR",
      "awsRegion": "us-east-1",
      "retentionInDays": 30
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-security-monitoring
  namespace: midterm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-security-monitoring
  template:
    metadata:
      labels:
        app: cloudwatch-security-monitoring
    spec:
      containers:
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent
          volumeMounts:
            - name: cloudwatch-config
              mountPath: /etc/cloudwatch
              subPath: cloudwatch-logs-config.json
      volumes:
        - name: cloudwatch-config
          configMap:
            name: cloudwatch-security-config
---

apiVersion: monitoring.coreos.com/v1
kind: AlertmanagerConfig
metadata:
  name: security-alerts
  namespace: midterm
spec:
  alertmanager:
    alertmanagerConfig:
      apiVersion: v1
      kind: Config
      alert:
        - name: HighErrorRate
          expr: |
            sum(rate(http_requests_total{status="5xx"}[5m])) by (service) > 1
          for: 10m
          labels:
            severity: critical
          annotations:
            description: "High error rate detected in service {{ $labels.service }}"
            summary: "HTTP 5xx error rate exceeded threshold."
