//Previous file: doctor-office-backend/k8-manifests/deployment.yaml - https://github.com/vi-kinn/Doctors-Office-Appointment-site/blob/main/doctor-office-backend/k8-manifests/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2 # Increased replicas for better availability and load distribution
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 474668414952.dkr.ecr.us-east-1.amazonaws.com/doctor-office-backend
          resources:
            requests:
              cpu: "0.5" # Adjusted to more reasonable values based on testing for load handling
              memory: "256Mi"
            limits:
              cpu: "1" # Optimized resource limits for better load handling
              memory: "512Mi"
          ports:
          - containerPort: 5000
      serviceAccountName: backend-service-account  # Added IAM Role to use appropriate permissions
