//Previous file: doctor-office-backend/k8-manifests/deployment.yaml - https://github.com/vi-kinn/Doctors-Office-Appointment-site/blob/main/doctor-office-backend/k8-manifests/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 474668414952.dkr.ecr.us-east-1.amazonaws.com/doctor-office-backend
          resources:
            requests:
              cpu: "0.3"            
              memory: "200Mi"
            limits:
              cpu: "0.7"            
              memory: "200Mi"        
          ports:
            - containerPort: 5000
      serviceAccountName: backend-service-account  # Added IAM Role to use appropriate permissions
